defmodule Identicon.Image do
	@moduledoc """
		Hold struct - all the data inside the application Identicon

		Initialize with default
		`%Identicon.Image{}`
	"""

	# hex property - list of numbers generated by md5 conversion
	# default value nil
	defstruct hex: nil, color: nil, grid: nil, pixel_map: nil

end